### ISSUE TITLE
Supervisors attempt to restart the same actor if terminated before restart completes

### ISSUE THREAD

**Issue by halorgium** [celluloid/celluloid#331]
In the scenario of an actor terminating repeatedly, the supervisor may handle the exit event while the previous exit event is still being handled. 
There is no easy way to guard against this, but we should not crash the supervisor. 

[Repro](https://gist.github.com/halorgium/a4b1759c6e4ec45c4df5)

**Comment by felixyz** [comment]
This is probably the one thing in Celluloid that causes me problems most often. If I understand @tarcieri:s comment on #233 correctly, this is not really considered problematic behavior? Or is there a difference between what @halorgium describes here and #233?

It seems a similar problem occurs when `finalize` crashes: the supervisor end up crashing too and my app dies (I can link a repro if needed). This means I have to be really careful what I put in `initialize` and `finalize`. More specifically, setting up connections of any kind in `initialize` is out of the question unless I want to rescue any possible exception that could arise, which seems to go against the "let it crash" principle. You can argue I should not do such things in `initialize` anyway and I'd agree, but with `finalize` it's different: here is my last chance of cleaning up and if any unforeseen exception is raised (for example due to trying to close a connection that was already closed, which caused the actor to terminate in the first place) the supervisor will go down.

Since, as I said, this is one of the trickier parts of using Celluloid for me, I'd like to ask about the status of this issue.

Is this not considered a problem? And if so, what are the recommended best practices?
If it is considered a problem, is there any consensus on or clear plan for how to handle it? And if so, what can I do to help?

**Comment by felixyz** [comment]
After some more thought I wonder if the "best practice" might be to have one more level of supervisor. My current top-level supervisor directly supervises several pools and actors. If one of them raises an exception in `initialize` or `finalize`, there goes my entire app. If I had one more supervisor above my current top-level supervisor that wouldn't be the case. The rule of thumb then would be: "The top-level supervisor is only allowed to supervise other supervisors:" Opinions on this?

**Comment by tarcieri** [comment]
On Thursday, February 12, 2015, Felix Holmgren <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> After some more thought I wonder if the "best practice" might be to have
> one more level of supervisor.
>
> Yes. You're describing the idea of a supervision tree, which is supported
by Celluloid and used heavily by both Erlang and Akka.

>  My current top-level supervisor directly supervises several pools and
> actors. If one of them raises an exception in initialize or finalize,
> there goes my entire app. If I had one more supervisor above my current
> top-level supervisor that wouldn't be the case. The rule of thumb then
> would be: "The top-level supervisor is only allowed to supervise other
> supervisors:" Opinions on this?
>
A supervision tree is definitely the way to go.


-- 
Tony Arcieri

**Comment by digitalextremist** [comment]
Moved to: celluloid/celluloid-supervision#5
