### ISSUE TITLE
Remove supervision oriented instance methods. Implement Supervisor configuration object.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#506]
Per discussion on #503 and #505, we are making a breaking change to `master` but will keep the old-style API in `0-16-stable` ... the breakage will be as follows:

There will be no `supervise`, `supervise_as` or `pool` instance methods available actors.

All implementations of those methods will be `Class` methods going forward. No `Instance` methods available, as they are unsafe.

Additionally, supervision configuration will be handled by the creation of a new object which can be instantiated and prepared in a single-threaded context and potentially reused across various actors.

**Comment by digitalextremist** [comment]
Here are the instances of `supervise', `supervise_as` and `pool` methods we currently have:

```
Celluloid::ClassMethods.supervise
Celluloid::ClassMethods.supervise_as
Celluloid::ClassMethods.pool

Celluloid::SupervisionGroup.supervise
Celluloid::SupervisionGroup.supervise_as
Celluloid::SupervisionGroup.pool

Celluloid::SupervisionGroup#supervise
Celluloid::SupervisionGroup#supervise_as
Celluloid::SupervisionGroup#pool

Celluloid::Supervisor.supervise
Celluloid::Supervisor.supervise_as

```

It seems the ones being annihilated are those instance methods on `SupervisionGroup`

And it seems the object being created is `SupervisorConfiguration`

/cc: @tarcieri

**Comment by e2** [comment]
1. Please keep the master branch "releasable" at all times - you never know when you'll need a quick bugfix (and handling branches, backports, cherry-picking is all a big waste of time).
2. Don't break compatibility unless it's absolutely necessary to move forward - Ruby makes it easy to move code into deprecated classes which can be easily removed later (along with their specs)
3. At least keep the specs in sync with the changes - with a lack of docs, specs are the last bastion of sanity (`git blame` sucks as a replacement for documentation)
4. Give examples of the "configuration object" before you start implementing it - I don't see it as absolutely necessary (given the existing options are better documented)

A extra few comments:
- `Celluloid.pool` and `SupervisionGroup.pool` are unrelated (the first uses `PoolManager.new`, the second `PoolManager.new_link`)
- fix #508 should keep things backward-compatible and help clarify the argument handling (which isn't well defined to begin with)
- `Celluloid.supervise` is just a convenience wrapper for `Supervise.supervise` (which in turn is just a convenience wrapper for `SupervisionGroup.add`
- I'd deprecate `supervise_as`, because it add more bloat than it's worth
- `SupervisionGroup.pool` and `SupervisionGroup.supervise` both pretty much just call `SupervisionGroup#add` - with just one option different

**Comment by tarcieri** [comment]
@e2 that's not how Celluloid is developed. We specifically maintain `*-stable` branches for what you suggest using master for, and reserve the right to break master at any time. If you don't like that, tough?

The supervisor system is fucked and we need to fix it. This will result in breaking changes.

Having a configuration object allows people to build supervisor configurations in the OO-style they are trying to do today by building up state in actors, however actors are ephemeral.

**Comment by e2** [comment]
> If you don't like that, tough?

I just discourages from contributing (not that I do much myself) if PRs by default are expected to be mergeable with master - and yet it's ok for master to have failing unit tests. 

It would be nice to at least mention this in the README section on contributing.

There's no roadmap, so I don't know if I should lock to release such as ~0.16.x or ~0.x. And while there are version-specific stable branches, there's no "general" stable branch, e.g. `stable`.

It's counter-intuitive for a project with no 1.x.x version to have multiple "stable" branches and be dealing with backporting as the default policy.

> The supervisor system is fucked and we need to fix it. 

It never was even "finished" AFAIR (based on the docs).

> This will result in breaking changes.

I don't mind changes breaking compatibility or even features - as long as there are some unit tests to "document" those changes as intentional.

It's allowing failing unit tests as the "norm" on master that I find detrimental - especially with a project with minimal docs to begin with. Sure, tests can break after a merge, or as the result of human error, etc. I get that. I don't mind an occasional quick hack merged without Travis giving it a thumbs up...

... I just think failing unit tests on master as "business as usual" are detrimental. (Might as well just disable Travis on master). Am I wrong?

If the changes are going to be breaking so much, is there a 1.x planned ahead? Or will the incompatibilities be released as 0.17.x? 

(If so, I'd lock to 0.16.x and test against possible 0.17.x.preX versions in development).

Anyway, I'm just mentioning this FWIW as simply confusing/baffling/discouraging - maybe it's just me.

> Having a configuration object allows people to build supervisor configurations in the OO-style they are trying to do today by building up state in actors, however actors are ephemeral.

Good point. I'd love to see some proper examples/ideas on how to properly handle state though - even given the current implementation (which would make the needed rework more obvious).

**Comment by tarcieri** [comment]
> There's no roadmap, so I don't know if I should lock to release such as ~0.16.x or ~0.x. And while there are version-specific stable branches, there's no "general" stable branch, e.g. stable.

A "general" stable branch doesn't make any sense, because we're introducing breaking changes between releases.

Let's imagine we merged the supervisor changes onto the "stable" branch, and you're just tracking HEAD. Now your code is broken.

Pinning the stable branches to releases means that your code (theoretically) won't break, and when you're ready to move from e.g. `0-16-stable` to `0-17-stable`, you can make the corresponding changes to your code to support the API changes.

There's ample precedent for this sort of branching scheme and I think it's exceedingly common.

> It's counter-intuitive for a project with no 1.x.x version to have multiple "stable" branches and be dealing with backporting as the default policy.

Celluloid should've probably already had a 1.x release already. But given its wide usage we try to maintain some modicum of stability.

I'm really confused by all your arguments, as I think every single change you're proposing would make things quantitatively worse than how things work today.

> It's allowing failing unit tests as the "norm" on master that I find detrimental - especially with a project with minimal docs to begin with. Sure, tests can break after a merge, or as the result of human error, etc. I get that. I don't mind an occasional quick hack merged without Travis giving it a thumbs up...

Celluloid has a creaky test suite and I both apologize for that and appreciate your work towards trying to fix it. We should probably just skip all flaky tests in the suite (but leave them there in case someone would like to improve them so they aren't flaky)

**Comment by e2** [comment]
> A "general" stable branch doesn't make any sense, because we're introducing breaking changes between releases.

I think I get what confused me:
1. Basically, the minor version according to semver is a major version (API - incompatible) in Celluloid.
2. But, 0.15.x and 0.16.x were only slightly incompatible (overall, no difference in API)
3. It took about a year to release 0.16.x - with lots of people checking out celluloid/master in the meantime (mostly for bugfixes)
4. Releases were based off of master anyway
5. Based on comments in issues it seemed like the project is a "mess" with a lot of willingness to "clean up", but without much time/resources on hand to do so
7. Given the state of tests it seemed "risky" to ask for bugfix releases - and given the "distance" between releases and the version < 1.0  it seemed strange to ask for backporting

> Celluloid should've probably already had a 1.x release already. But given its wide usage we try to maintain some modicum of stability.

I'd move to 1.x simply for SemVer purposes - Celluloid 0.16.x is very stable already for a 1.x candidate. Sure the API needs rework here and there, but there's not harm in releasing changes as 2.0 (especially for an overhaul). 

People could just lock to 1.x and forget about compatibility until 2.x - and this really what I realize I wanted.

I also realized there aren't that many commits (and ongoing changes) to warrant many releases (I though the project was more active) - so I agree backporting is strangely means less work. Especially since 0.16.x *is* the current *major* version.

So I all I really need is to lock to 0.16.x (expecting bugfixes in the minor version field) for as long as that version is supported (and maybe a deprecation warning in the "last" 0.16.x version) - because, I can pretty much count on 0.17.x *not* being API compatible.

It would help to mention this in the README (and suggesting '~0.16.0' in the `Gemfile` example there).

Anyway, I appreciate the time you took explaining this - and I really look forward to the upcoming changes.

Thanks!

**Comment by digitalextremist** [comment]
This ticket became a conversation so it's superceded by #511 which we can keep clean.
