### ISSUE TITLE
deadlock detection and resolution system

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#509]
Per the Ruby `GSoC` Ideas List, there is this project:

https://github.com/rubygsoc/rubygsoc/wiki/Ideas-for-Celluloid#deadlock-detection

> In systems with complex interaction between Actors, it is possible for deadlocks to occur. This is particularly true when using the exclusive feature to force in-order processing of messages. Finding and debugging these deadlocks is very difficult. Creating a "deadlock detector" thread or providing more robust logging would be very useful for solving these issues when they arise.

This specialized Celluloid thread/actor needs to:
- Determine the correct criteria for declaring an actor as being deadlocked.
- Audit actors running _efficiently_ without causing a deadlock itself.
- Detect deadlocked actor(s).
- Log the event.
- Resolve the deadlock in some way:
  - Sleep one actor and let others pass.
  - Kill one actor and others pass.
  - Kill all deadlocked actors, if supervised and fault-tolerant?
- Be sure the resolution occurs and continue auditing.

The most important things here are not to compound a deadlock by getting the deadlock system tied up in it, causing another deadlock, and having no false-positives where actors which are not deadlocked are handled as if they were deadlocked.

There will need to be a reproducible deadlocking test application created, and tests added which can reproduce a deadlock based on that. Once this feature is added, that deadlock test ought to pass.

The deadlocking subsystem ought to be easily disabled.

**Comment by e2** [comment]
The only reason you get a "deadlock error" in MRI is because of the GIL. You can detect that situation manually in some cases by checking the Thread.list entries for threads that are sleeping - because of the GIL, if all threads are asleep, you have a deadlock.

On JRuby however, even if all threads are asleep, it doesn't mean there's a a deadlock - all threads could be a sleep, but one thread could have just done `sleep 2` and will soon wake up itself and/or everyone else.

A solution would be to have "another main thread" (a watchdog thread) that is never allowed to sleep - and whenever e.g. `Kernel.sleep` is called, it could check if all other threads are sleeping - and provide a warning at least (which actors are waiting on messages, which are sleeping for other reasons).

Timeouts are another way to prevent deadlocks - they are simply like that watchdog thread I mentioned, only local+temporary.

Summary: to not have deadlocks on JRuby (or even MRI), the *user* has to *explicitly* define how long a task can continue to sleep before it's considered "deadlocked".

**Comment by digitalextremist** [comment]
Thanks for the notes @e2. Our potential Google Summer of Code student, @dilumnavanjana is hoping to get a paid internship to work on this.

We're talking about the possibility of having all the `ActorSystem` or `Group` actors periodically checked. Going through the entire `Thread.list` array would touch internals that are probably not a good idea to pause/restart.

You're right there are gotchas. Sleep could really be sleep, and finding an Actor in a sleep state - rechecking later then finding it "again" could be another sleep state after a spurt of work was legitimately done. One thing I thought was to find a performant way to tag tasks with an identifier so that when passes are done to audit the actors, it can be verified that a sleep state truly is an extended sleep possibly indicating a deadlock. That'd take a pretty solid benchmark to be sure we aren't adding a lot of overhead to each task run.

> This `Unlocker` system ( borne by a watchdog thread ) ought to be easy to turn off. But I'd use it.

There should be an overall, configurable ceiling timeout, but also actors ought to have a local timeout associated with them. I've experimented with this before though, and it's a bit of a pain. A lot of deadlocks can be *created* by putting in an actor to audit and manipulate other actors.

I think this would be most effective with something like #550 happening concurrently.

The hope though is for our potential student to become sufficiently aware of `Celluloid` to remain part of the community long-term. He is already showing signs of sincere interest in `Celluloid` so this would provide a long enough term to really test him out and let him feel-out our codebase and contributor community.

**Comment by e2** [comment]
> Going through the entire Thread.list array would touch internals that are probably not a good idea to pause/restart.

I didn't mean `Thread.list` specifically, especially since even JRuby fibers appear there as threads. I think deadlock detection should be Supervisor specific or something. Deadlocks are also closely related to dependencies, though dependencies between actors are hard (or even impossible) to discover.

There's also the main thread - calling a `join` from there on a sleeping thread will deadlock on MRI, but on JRuby you'll have to be aware of the main thread to detect this. It's also one of the reasons I'm currently trying to avoid/get rid of `Actor.join`.

> One thing I thought was to find a performant way to tag tasks with an identifier

This is somewhat achieved with API like `Thread#celluloid?` (and friends) and detecting the kind of sleep in `StackDump` (sleep-waiting for message, vs sleeping for another reason).

I'm actually using something similar to know if an task can be "safely killed" (which is actually an oxymoron on JRuby...). Here, killing/raising will likely be needed to ehm... "resolve" deadlocks.

> Sort of like specifying TTL in DNS

That's a good example. 

I think the "criteria" for a deadlock is: "will the actor respond to a TerminationRequest in a 'reasonable' amount of time?". 

Maybe mailboxes can do most of the heavy-lifting with deadlock detection?

**Comment by digitalextremist** [comment]
What I was thinking for the identifier was more like a `UUID` ( but fast to create ) that would specify where the `Actor` really stands. When the task completes, the method call or whatever it is, the next one gets another identifier, so when `.busy? === true` or `status` returns `:busy` there can be a reference for what it's busy *with* so when a return pass is done to see if it's "still busy" we can know that it's "still busy" and not "busy again" ... there's probably a precedent for this in Erlang/Akka or something.

**Comment by tarcieri** [comment]
`Celluloid.uuid` is already quite fast and in the critical path for all method invocations

**Comment by digitalextremist** [comment]
Remember when I had that problem though, where I'd have 5-90 second delays in generating `UUID`'s? I'm not quite beyond that fear. I solved it outside `Celluloid` by installing `haveged` to have more enertia, so we may want to do an enertia test ( in general ) ... but glad to hear it can be a `UUID` then!

**Comment by e2** [comment]
@digitalextremist - there are also race conditions here: a task can be "busy" when you check the status ... and then be sleeping while you're checking another. So even if you detect a thread as "busy", it can actually be the cause of a deadlock a fraction of a second later...

**Comment by tarcieri** [comment]
@digitalextremist that only happens at boot

**Comment by e2** [comment]
@tarcieri - lol, just imagine the solution to gathering entropy: "please move your mouse and press keys on the keyboard while Celluloid gathers enough entropy to continue...".

**Comment by digitalextremist** [comment]
@e2 ... on a virtual machine in a cloud no less :)

**Comment by tarcieri** [comment]
`/dev/urandom` is (supposed to be) a CSPRNG seeded at boot. I believe the problem @digitalextremist was talking about involved Docker containers or something?

**Comment by digitalextremist** [comment]
@tarcieri yes, I have a network of DigitalOcean droplets  ( virtual  machines ) with nearly no entropy, or not enough to go around. It used to be user input or network traffic provided a sufficient generator of synthetic randomness but only haveged provides my cloud based instances with entropy by using the processes on the system as a source of synthetic randomness. It was hard to pinpoint a 3-360 second delay based on entropy depletion. Now it regenerates in milliseconds!

**Comment by digitalextremist** [comment]
@dilumnavanjana I am moving this into `0.17.5` because it seems you are making solid progress in your learning process. I'm sorry I've not been as available as I'd like. I am actually working hard to spare you the madness of `0.17.0` so you can code on this in a clean release. If you are accepted to take this project on under `GSoC` sponsorship I am relying on using the time allotted in that to work together, so please don't interpret my excessively busy streak as how it will be once `GSoC` starts. Keep going strong!

**Comment by digitalextremist** [comment]
Congratulations to @dilumnavanjana on being accepted into `GSoC` in the first `Ruby` organization since 2009, to come work on this issue. I've invited you into the `v1-taskforce` to come accept this assignment officially.

**Comment by dilumnavanjana** [comment]
Thanks @digitalextremist for your support last few weeks, got the `v1-taskforce` invite.

@e2 Are you suggesting a separate watchdog thread to keep eye on `sleep`, `wait`, `terminate`?

**Comment by digitalextremist** [comment]
You are very welcome @dilumnavanjana, I think you will do very well.

Check out `Celluloid::Group::Manager` starting to be developed.

**Comment by e2** [comment]
> @e2 Are you suggesting a separate watchdog thread to keep eye on sleep, wait, terminate?

Needs a specific use case. It's best to start with a spec illustrating the problem.

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
