### ISSUE TITLE
Deal with :flaky tests.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#524]
Tests marked `:flaky` either need to be fixed, or removed from the test suite ( commented out to be addressed later ).

**Comment by e2** [comment]
Failing tests marked as `:flaky` should be currently be rerunning - both locally and on Travis, so I see no reason to remove them, really.

I chose these values: https://github.com/celluloid/celluloid/blob/master/spec/spec_helper.rb#L57 because the tests should work "most of the time" and fail only "occasionally". If a test fails "more often" it's better to put a small sleep() here an there (as much as I see them as pure code smells) and get it "working most of the time" again.

Flaky tests are actually a side-effect of not using isolated tests (e.g. with mocking). Ideally, Celluloid itself shouldn't be using Threads (or Fibers on JRuby) at all.

I'm just saying that the "flakyness" of tests is a symptom of much bigger problems.

Other than that - Celluloid needs an overhaul on the "testing support" side. I'm thinking of things like CELLULOID_DEBUG, CELLULOID_MONITORING, mocking task classes, Travis environment variables for task class (and refactor out the RSpec shared examples).

It's too easy to scapegoat "flaky tests" - and disregard actual, genuine race conditions in Celluloid (or even bugs in  JRuby).

I think each "flaky" test should have it's own issue (or grouped at least if they are related).

**Comment by e2** [comment]
Some tests just need to marked as flaky, e.g. if this build today failed because this test if flaky - then this test simply needs to be marked as such (it isn't as of master):
https://travis-ci.org/celluloid/celluloid/jobs/56532489#L643

**Comment by digitalextremist** [comment]
I wholeheartedly agree @e2. I'd be interested in cleaning these up with you if you're willing.

**Comment by digitalextremist** [comment]
In dealing with `:flaky` tests, it seems one issue is killing Threads between tests, which under jRuby means killing Fibers also, which causes a melt down.

But then when you avoid the meltdown, the tests start failing intermittently, because now there are undead Threads/Fibers wandering around.

**Comment by digitalextremist** [comment]
A recent search through the codebase(s) shows no `:flaky` tests. It seems we can remove the evidence of there ever having been, then this is done.

**Comment by e2** [comment]
@digitalextremist - this can be closed. If there are flaky tests, those should be individually opened as new issues.

**Comment by digitalextremist** [comment]
We just need the metadata checks and environment variables allowing then removed.

**Comment by e2** [comment]
@digitalextremist - already done on my experimental branch
