### ISSUE TITLE
Set RuboCop loose in codebase.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#538]
> At some point I'd like to get most of the RuboCop violations --auto-corrected and have a sane RuboCop policy too. -- @tarcieri ( #537 )

After `0.17.0` or `0.16.5` is ready for a prerelease, and all the #529 branches are audited, implement Robocop policies and bring the codebase up to standard.

**Comment by e2** [comment]
I've "hidden" the current offenses here: https://github.com/celluloid/celluloid/pull/539

It's best to decide which ones are essential to reenable (by simply removing them from the `.rubocop_todo.yml`, and which ones to ignore for now (like line-length).

Probably the best to start with are the infrequent ones that can be autocorrected - as long as it doesn't interfere with merging, etc.

/cc @tarcieri

**Comment by tarcieri** [comment]
I'd suggest blowing away any extant config, running --auto-correct, then getting a baseline.

I am guessing we'll have to crank up things like ClassLength/MethodLength/AbcComplexity up quite a bit.

Beyond that, we can bikeshed about various details. I'm a fan of `Style/StringLiterals: EnforcedStyle: double_quotes` :wink:

**Comment by e2** [comment]
@tarcieri - I did that. The `.rubocop_todo.yml` in #539  is a "fresh list" of all the offenses.

> I am guessing we'll have to crank up things like ClassLength/MethodLength/AbcComplexity up quite a bit.

RuboCop already took care of that - it displays the largest found size (176 characters - if someone creates a longer line, it will be visible, while anything less - will be skipped).

> I'm a fan of Style/StringLiterals: EnforcedStyle: double_quotes ￼

413 offense - I wouldn't do it because merging could get in the way.

I did a test - here's what auto-correcting ALL the current offenses would look like:

https://github.com/e2/celluloid/commit/c6d6e1d45cd3f83f4afac0a766154acd7c647e68

No major benefit really in the current codebase IMHO.

**Comment by e2** [comment]
I just switched to double quotes (less offenses): https://github.com/e2/celluloid/commit/64faa823e73f6d408aacb9afc8f399ccdf70dad0

**Comment by digitalextremist** [comment]
@e2, you are a monster.

I agree, this is largely trivial at the moment and best run at the turn of `0.17.0` when we're within range of `1.0` ... otherwise this is just going to obfuscate our remaining steps to release. But it's all set though.

**Comment by tarcieri** [comment]
I like https://github.com/e2/celluloid/commit/64faa823e73f6d408aacb9afc8f399ccdf70dad0 FWIW

**Comment by digitalextremist** [comment]
:+1: e2@64faa82

**Comment by e2** [comment]
Yeah - though backporting would become a pain in the ass. Definitely. 99% of life guaranteed to be spent resolving git conflicts... unless you change the README or something.

It would probably have to be done both on 0-15-stable, 0-16-stable and master at the same time.

**Comment by digitalextremist** [comment]
Do we need to backport? If we're marching to `1.0` can't we just pick a clean point and not look back?

**Comment by e2** [comment]
I meant cleaning the offenses would have to be done on all branches, so backporting isn't a problem.

**Comment by e2** [comment]
@digitalextremist - once we get to this, I'd fix the "double quote" offenses as one separate commit. 

The same with every other offense where there's more than one or two - especially since fixing some offenses may (re)introduce memory leaks. (At the very least it's best to be able to bisect).

Also, large RuboCop-fixing commits are tough to work with - unless a single commit addresses a single offense.

**Comment by digitalextremist** [comment]
When the time comes, I will step through offense-by-offense and remedy the branch @e2.

**Comment by digitalextremist** [comment]
This was done, and all the remaining issues will need to be gone though one by one and either used as a prompting to change the rules, or handled in `0.17.5` item-by-item changes posted as their own issues and labeled `style` if they are not just obvious fixes.
