### ISSUE TITLE
Fault Tolerant Actors with Work Histories

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#550]
This would be a special version of Supervised Actor ( #511 ), and/or Supervised Actor Pool, which would be to save the 'work order' before hitting the Actor with it, then testing if the work was completed. Ideally this would be a type of `Proxy`, or a `Proxy` plugin that keeps a work history.

If work is not completed, and especially if it deadlocks ( #509 ) and it gets assassinated for the good of the system, the "work order" ought to be retried a certain number of times. If there is no success after `x` times then its failure is terminal. Along the way each try is announced into the log, etc.

And not to create an all-new Garbage Collection problem, work order history ought to have a very zealous purger mechanism and a ( configurable ) realistic half-life. But in situations where Fault Tolerance is needed, extra resources will be budgeted without hesitation.

Suggestions made here can also be addressed:
- https://github.com/celluloid/celluloid/wiki/Fault-Tolerance

**Comment by tarcieri** [comment]
Are you thinking something like this?

http://doc.akka.io/docs/akka/2.1.0/modules/durable-mailbox.html

I would avoid 1) inventing anything new for this and 2) anything more complex than a durable mailbox

**Comment by e2** [comment]
To me, fault tolerance is about "fault isolation" and not "fault handling". 

"Work orders" seem app-specific because of potential side effects (e.g. referencing another actor through the registry). 

Whether a "work order" is transactional or atomic or simply resumable or not ... I'd say another supervised actor can simply monitor the workload instead.

I'd also imagine that shutdowns would become horribly complex if "transactions" were introduced on top of the "afterthought" which shutdown/termination logic currently is.

**Comment by tarcieri** [comment]
Closing as stale. If you are still interested in this issue, please reopen it.
