### ISSUE TITLE
Outputting to stderr for CI?

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#566]
Should we be outputting to stderr for CI tests? Seems like we might want to automatically gist those. A blizzard of errors in the CI output makes passing tests seem failed, since tests intentionally spam the logs.

**Comment by e2** [comment]
> blizzard of errors in the CI output makes passing tests seem failed
The blizzard of errors is *precisely* the problem. Need proper mocking/stubbing.

Tests need to be told which errors are expected (intentional crashes) and which aren't.

They are just like warnings - they shouldn't be there.

**Comment by e2** [comment]
I've already once pushed a changed that "passed" but was actually a test silently crashing - way too dangerous to *not* have errors on STDERR.

We don't even check logs on Travis to begin with - besides, Travis considers the output as a log anyway (that's why it's downloadable).

Not to mention - STDERR is usually either line-buffered or buffered synced with the normal output, while logs to files are buffered or synced manually (which slows down tests on Travis unnecessarily).

**Comment by digitalextremist** [comment]
Abandoning in favor of visible log spam, so we know what's happening and fix it. May revisit later with email reports, gists, etc.
