### ISSUE TITLE
recursive requirement of gems

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#586]
This is probably easily fixed. I've tried several arrangements and have not reached one that works all the time. Right now, as you may have noticed, either `celluloid` passes its tests and all the gems fail, or all the gems pass and `celluloid` fails. Reason being, there is a circular/recursive gem requirement issue.

Right now, it's in a mode where `celluloid` depends on the gems, so the gems cannot each depend on `celluloid` but ideally, it ought to go both ways. *Technically, the gems ought to be unmentioned in `celluloid` at all, but some tests and examples need gems, so they are included -- more so, they are not only supposed to be installed but required, for backward compatibility at the moment.*

The only way to get `celluloid-*` to 'install' it seems is to list gemspec dependencies, versus just putting gems into the Gemfile, such as `celluloid-supervision`, etc. But as soon as the gemspec for `celluloid` holds any one of the gems, each of those gems may *not* even list `celluloid` in their Gemfile!

Ordinarily it'd be easy to just list `celluloid` in the gems' `Gemfile` and list all the individual gems in the `celluloid` `Gemfile` and not mess with the `gemspec` for any of them... but putting gems in the `Gemfile` of `celluloid` is not getting them installed for some reason, unless explicitly listed as a dependency!

**Comment by e2** [comment]
@digitalextremist - I'd strongly consider moving current Celluloid stuff into 'celluloid-core' and have 'celluloid' depend on 'celluloid-core' and everything else it needs. 

This is doable, but it will take more time than expected - and there's the pressure of time to get a release, right?

This is a tough choice between compatibility and "elegance". I'd pick "elegance" because keeping compatibility has a huge overhead (to the point that even fixing bugs can't happen without breaking API compatibility).

But, it's best to take this case by case. 

Ultimately, I think supervision can be removed from Celluloid completely - I'll try and get that working and let you know here. (There is some overlap with the Reaper and I have some insights after attempting to remove supervision-dependent stuff from the Probe specs).

Meanwhile, I'd strongly suggest "moving" the current codebase to 'celluloid-core' and making 'celluloid' just a wrapper for dependencies (omnibus like). But that's a compatibility/organizational thing - and I don't want to get involved.

This should've been done sooner - it would've allowed moving code between 'celluloid' and 'celluloid-core' as necessary (e.g. simply moving stuff into 'celluloid' instead of gems).

Long term though - IMHO celluloid definitely needs a "slim", "protocol-only" 'celluloid-core', so either we pay the price sooner ... or later (when more stuff compounds).

**Comment by e2** [comment]
Supervisors removed here: https://github.com/celluloid/celluloid/pull/587

**Comment by e2** [comment]
@digitalextremist - I think the choice is between keeping compatibility (and putting strategically worthwhile effort into extracting celluloid-core) or telling people in the upgrade notes to include any extra gems they need.

I think the safest option is the upgrade notes (and telling people to add deps explicitly). If this becomes too troublesome for people testing the pre-release ... then you can always switch back to extracting code into a 'celluloid-core' gem (since it seems the only other option).

**Comment by digitalextremist** [comment]
Went the other way, but thank you -- extracted `Internals`, `Probe`, `Notifications`, and `logging/*` to `essentials` as well as requiring `-supervision` from there. It's a bit messy in the gemspec on each gem but overall it's fine for now.
