### ISSUE TITLE
add fork() fix to 0.18.0 ( scrapped from 0.16.1 )

### ISSUE THREAD

**Issue by e2** [celluloid/celluloid#612]
@digitalextremist - could you release 0.16.1 with #513 ? Basically Celluloid terminates with an error without it, and it's already causing problems with multiple gems using fork().

**Comment by e2** [comment]
NOTE1: This patch is not on 0-16-stable (it's been reverted)
NOTE2: this patch should be applied to the Spawner as well

**Comment by digitalextremist** [comment]
Where was it reverted?

**Comment by e2** [comment]
Here: https://github.com/celluloid/celluloid/commit/6226a68cd6adf63440c70bcb7a1d7ed68f85ce87

(The revert was merged, not the patch).

**Comment by digitalextremist** [comment]
Alright, I see this and don't see a problem putting the patch into `0.16.1`

**Comment by e2** [comment]
@digitalextremist - any update on this?

**Comment by digitalextremist** [comment]
@e2 I cherry picked that for you, and cut `0.16.1` just now. If you would be willing to reapply the patch to `0.18.0` in its current incarnation and PR that, I'd appreciate it. Otherwise I'll eventually remember to do that, but not for a long time. Please confirm your situation is sorted out now.

**Comment by e2** [comment]
Listen doesn't use celluloid since 3.x, so I personally am not experiencing this anymore - and so I don't have a celluloid project to test a PR against. 

It's unlikely this problem will reoccur, and if it does, it isn't complex to fix with an similar patch.

**Comment by sebyx07** [comment]
-v '0.16.1' is yanked, can you revert this ?

**Comment by digitalextremist** [comment]
Yes, this is yanked. And the piece of logic in this will come back in at `0.18.0` for those following the path forward. Maintaining the previous series of versions has proven to be like trying to brush removed molars, so that'll just stop. If people want what was `0.16.1` then they can pull in `0-16-stable` directly from the repository... but `0.18.0` ought to dramatically out-perform the `0.16.0` line, as the `0.17.0` line already does in many different ways. Whatever ways it lacks currently, will resolved in `0.18.0`

**Comment by bluej100** [comment]
The most recent version of sidekiq still depends on the 0.16 branch: https://rubygems.org/gems/sidekiq/versions/3.4.2 .

**Comment by digitalextremist** [comment]
Yes, and it was just updated to use `0.17.*` over the last 7-10 days, so that'll be nice to see it released.

**Comment by bluej100** [comment]
Terrific. Thank you.

**Comment by cryptojuice** [comment]
Would have been nice if this was pulled after Sidekiq released a new build with 0.17.x. A number of us aren't working directly off Sidekiq's master branch.

**Comment by BlakeBosin** [comment]
The problem with yanking gems, is when other gems have coded dependencies on your gem.  Example of some of the tools we use that use this gem are Ridley and Berkshelf, Omnibus.  We normally have these top level gems versioned locked because we support online operations.  Its one thing to yank a gem the same day it's released, but after it's been out for sometime, you should have a really good reason to remove it.

**Comment by bluej100** [comment]
Yeah, we've just dropped back to 0.16.0 for now, which hardly seems like behavior to encourage. I would appreciate it if you would at least leave it up until major dependent projects publish new versions with updated dependencies.

**Comment by jmanero-r7** [comment]
An other alternative would be to re-release the reverted code-line, e.g. `0.16.0` as `0.16.2`. This would have the effect of reverting the code, but keep sane resolution for anything locked on the `0.16` line (especially with `~> 0.16.1`, like `berkshelf@3.3.0`).

**Comment by pda** [comment]
> An other alternative would be to re-release the reverted code-line, e.g. `0.16.0` as `0.16.2`

Yes please — yanking published versions just causes pain around the world. We've currently got broken `Gemfile.lock` files with 0.16.1 pulled in by sidekiq.

**Comment by aianus** [comment]
+1, please don't yank published versions.

**Comment by cconstantine** [comment]
+1, please don't yank published versions.

**Comment by tarcieri** [comment]
Duly noted, you can cease the +1s now

**Comment by cconstantine** [comment]
Thanks.  Celluloid is some good stuff.  The fact that people care after even a few days of being out shows that people like and use it. :)

**Comment by digitalextremist** [comment]
Re-resolved in 8d8f1d460d7916598da875291b8e5ea68f948d3a, and incidentally already in `0.16.1`
