### ISSUE TITLE
Produce deadlocks various ways.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/celluloid#624]
- [x] Research various ways to create deadlocks and share those here.
- [x] Produce examples for each way to create a deadlock.
- [x] Create test specs with those examples.
- [x] Let the test specs fail, until #509 is working ( which is how you will know )

**Comment by dilumnavanjana** [comment]
Able to create 3 deadlocks,
1 - From `Mutex.lock`
2 - From `Mutex.synchronize`
3 - From Celluloid `exclusive`

Here are the results for various rvm versions,

For `Mutex.lock` & `Mutex.synchronize`  on `ruby-2.1.1` gives an error message
`ERROR -- : Actor crashed! ThreadError: deadlock; recursive locking`

For `Mutex.lock`  & `Mutex.synchronize` on `jruby-1.7.19` doesn't give any error message, the program waits because of the deadlock.

For `Mutex.lock`  & `Mutex.synchronize` on `rbx-2.5.2` gives an error message
`ERROR -- : Actor crashed! ThreadError: Recursively locking not allowed`
 <hr>

For `exclusive` on `ruby-2.1.1` gives an error message finally
`Couldn't cleanly terminate all actors in 10 seconds!`

For `exclusive ` on `jruby-1.7.19` &  `rbx-2.5.2` doesn't give any error message, the program waits because of the deadlock.

**Comment by digitalextremist** [comment]
Excellent! I was hoping for silent deadlocks most of all. Can you also research i/o related deadlocks? I'll look into what you have so far while you do that.

**Comment by dilumnavanjana** [comment]
I created an I/O related deadlock by `File LOCK_EX`

It doesn't give any error message for `ruby` , `jruby` & `rbx`. Seems it's a good sample for our testing.

**Comment by digitalextremist** [comment]
Excellent. I'm going to create a `GSoC` branch for you to submit your test suite and examples to, using the existing conventions and file locations.

**Comment by digitalextremist** [comment]
Here's that branch: https://github.com/celluloid/celluloid/tree/GSoC/2015

**Comment by dilumnavanjana** [comment]
spec fails as expected,

With `ruby` there is only one failure (I/O related deadlock `File LOCK_EX`)
With 'jruby` & `rbx` all the specs fail.

**Comment by digitalextremist** [comment]
@dilumnavanjana seems like some changes to the branch crept in. When did you pull in the `GSoC/2015` branch?

**Comment by digitalextremist** [comment]
Made comments on your PR //

**Comment by dilumnavanjana** [comment]
Shall I recreate the branch from `0.17.0-prerelease` & add the spec files?

**Comment by digitalextremist** [comment]
You can branch from `GSoC/2015` ... that is a branch off of `0.17.0-prerelease` ... which did you base your branch on so far?

**Comment by dilumnavanjana** [comment]
Now I recreate the `GSoC/2015` branch from `0.17.0-prerelease`. It'll work fine from now

**Comment by digitalextremist** [comment]
Did you see the rest of my notes on #628 having to do with paths and where to put your files?

**Comment by dilumnavanjana** [comment]
yeah, I'm working on them now

**Comment by digitalextremist** [comment]
Roger that.
