### ISSUE TITLE
Remove scary deprecation warning banner

### ISSUE THREAD

**Issue by mperham** [celluloid/celluloid#641]
Here's what's going to happen when you release 0.17.0.

1. People will install Sidekiq.  It accepts anything 0.16 and later.  sidekiq installs with 0.17.0.
2. Sidekiq requires 'celluloid/autostart'
3. Sidekiq prints big scary message upon startup.
4. @mperham gets deluged with issues from terrified users.

What can I do?

**Comment by tarcieri** [comment]
@mperham help us find a solution that doesn't annoy the hell out of Sidekiq users :wink:

**Comment by mperham** [comment]
I'm happy to opt into deprecation warnings.  Would you like me to treat Celluloid as a semver project and lock my dependency to major version?

**Comment by tarcieri** [comment]
@mperham that'd probably be the best approach for now. Lock to 0.16 until you're happy with 0.17.

**Comment by digitalextremist** [comment]
By the way, using `require 'celluloid/backported`' versus `require 'celluloid/autostart'` will show this:

```
Celluloid is running in BACKPORTED mode. [ http://git.io/vJf3J ]
```

That's a much less scary deprecation banner...

Ideally, once there is a sufficient patch, which I can put together, it'd be `require 'celluloid/current'` which has no warning at all, because it's using the most up-to-date API.

**Comment by mperham** [comment]
I'd ask that be the only banner.

**Comment by digitalextremist** [comment]
I'm good with that. Will do ( reopening )

**Comment by digitalextremist** [comment]
With this change being made, I am now cutting `0.17.0` official /cc: @tarcieri
