### ISSUE TITLE
Performance suffered after upgrade to 0.17

### ISSUE THREAD

**Issue by fedenusy** [celluloid/celluloid#681]
I want to relate my upgrade experience in case it's helpful to the core contributors (@tarcieri @digitalextremist). This is a very generic issue without repro steps, so feel free to close immediately after reading.

Initial stack:
- celluloid 0.16.0
- celluloid-io 0.16.1
- reel 0.5.0
- JRuby 9.0.1.0

After upgrade:
- celluloid 0.17.1.2
- celluloid-io 0.17.1
- reel 0.5.0
- JRuby 9.0.1.0

The upgrade started out fine, but performance degraded over time. Memory usage kept increasing without bound. Some actors which had never deadlocked before, began deadlocking.

I tried reproducing in a sandbox environment without success. The memory & deadlocking issues only seem to start occurring under heavy load.

I reverted to celluloid 0.16 and everything works fine.

I've read mention of issues between reel and celluloid 0.17. I'm not sure whether that's the root cause, but if you guys think that may be the culprit, I'd recommend locking reel 0.5 to celluloid 0.16.

**Comment by digitalextremist** [comment]
Will reply further, but a known leak is being fixed in 0.17.3 in a day or two. Stand by for more thorough response.

**Comment by digitalextremist** [comment]
This ought to be resolved completely in the next day or two, after the inclusion of #678 especially.

Also, `Reel` is at `0.6.0` but it has not been cut, because of some `jRuby` issues. So `0.6.5` will be released instead. All in all, there is a *lot* of code between `0.16.0` of `Celluloid` and `0.5.0` of `Reel`... so please reopen this after upgrading in the future, if the problems persist.
