### ISSUE TITLE
bug synchronization with conditions

### ISSUE THREAD

**Issue by kostya** [celluloid/celluloid#693]
i need some synchronization by hands, i used conditions for this

simplified example:

```ruby
require 'bundler/setup'
require 'celluloid/current'

class A
  include Celluloid

  def bla(x, sig)
    sleep(x)
    sig.signal(x)
  end
end

a = A.new
conditions = []

[1, 2, 1.5].each do |s|
  c = Celluloid::Condition.new
  a.async.bla(s, c)
  conditions << c
end

p conditions.map &:wait
```

but get a error
```
celluloid-0.17.2/lib/celluloid/mailbox.rb:63:in `sleep': No live threads left. Deadlock? (fatal)
```

**Comment by kostya** [comment]
i also trying to use future in signaling way:
```ruby
f = Celluloid::Future.new
f.signal(1)
p f.value
```

but get error:
```
celluloid-0.17.2/lib/celluloid/future.rb:142:in `value': undefined method `value' for 1:Fixnum (NoMethodError)
```

**Comment by tarcieri** [comment]
Conditions are level triggered. You need to be in a synchronized state to use them correctly. The API was changed at one point so they could be used across threads, but incorrectly so races like this crop up. They should probably be changed back so they're "pinned" to a particular actor/thread.

We should probably add a big warning to the documentation about this as the API is effectively unsafe in its current form.

In your example, you're kicking off an actor, the conditions are firing, but when you're not watching, and since they're level triggered you miss the events, then wait, but nothing else happens, so: deadlock.

You shouldn't use futures with that API either. Use:

`a.future.bla`

**Comment by kostya** [comment]
but how i can get future in such case? for method :add

```ruby
require 'bundler/setup'
require 'celluloid'

class A
  include Celluloid

  def initialize
    @queue = []
    async.run
  end

  def run
    loop do
      e = @queue.shift
      if e
        bla(e)
      else
        sleep 0.1
      end
    end
  end

  def add(x)
    @queue << x
  end

  def bla(x)
    p "starting sleep #{x}"
    sleep(x)
    p "end sleep #{x}"
    x
  end
end

a = A.new

a.add 1
a.add 2
a.add 1.5

sleep

```

**Comment by tarcieri** [comment]
```ruby
future1 = a.future.add 1
future2 = a.future.add 2
future3 = a.future.add 1.5
```

**Comment by kostya** [comment]
with this i just get future to adding event into @queue, which is milisecond, but how i can wait when every bla is end?

**Comment by kostya** [comment]
i expected something to work:

```ruby
require 'bundler/setup'
require 'celluloid'

class A
  include Celluloid

  def initialize
    @queue = []
    async.run
  end

  def run
    loop do
      e = @queue.shift
      if e
        bla(*e)
      else
        sleep 0.1
      end
    end
  end

  def add(x, f)
    @queue << [x, f]
  end

  def bla(x, f)
    p "starting sleep #{x}"
    sleep(x)
    p "end sleep #{x}"
    f.signal(x)
  end
end

a = A.new

a.add 1, f1
a.add 2, f2
a.add 1.5, f3

p f1.value
p f2.value
p f3.value

sleep
```
