### ISSUE TITLE
0.18.0.pre breaks Celluloid.running?

### ISSUE THREAD

**Issue by HoneyryderChuck** [celluloid/celluloid#748]
```ruby
> $ bundle exec pry                                                                           
[1] pry(main)> $CELLULOID_BACKPORTED=false                                                                 
=> false                                                                                                   
[2] pry(main)> require "celluloid"                                                                         
=> true                                                                                                    
[3] pry(main)> Celluloid.running?                                                                          
Celluloid::Error: Celluloid is not yet started; use Celluloid.boot                                         
from /home/.bundle/ruby/2.1.0/gems/celluloid-0.18.0.pre/lib/celluloid.rb:38:in `actor_system' 
[4] pry(main)>                                                                                             
```

**Comment by tsabat** [comment]
I've experienced this too.

**Comment by tarcieri** [comment]
This is at least partially intentional:

`require "celluloid"` does NOT call `Celluloid.boot`
`require "celluloid/autostart"` is the equivalent of `require "celluloid" && Celluloid.boot`

This allows tools using Celluloid as a library to avoid automatically starting Celluloid's background services simply by loading the library.

As far as what `Celluloid.running?` should do in this case, perhaps it should just return `false`. I am definitely open to that being the behavior here.

**Comment by HoneyryderChuck** [comment]
@tarcieri I get the meaning of the new require rules and I welcome them 👍  It's the `running?` call semantics which seem iffy. But since we are on the same page regarding that (about returning `false`), that'll make accepting the PR easier ;)

**Comment by tarcieri** [comment]
Please send a PR at your leisure

**Comment by HoneyryderChuck** [comment]
@tarcieri already did, weeks ago #749
