### ISSUE TITLE
Celluloid is unmaintained: looking for volunteer maintainers

### ISSUE THREAD

**Issue by tarcieri** [celluloid/celluloid#779]
If there are any volunteers interested in taking over maintenance of Celluloid, please reach out to me, either on this issue, or at my GMail address: bascule. I can help mentor you.

--

NOTE: Discussion about the future maintenance of Celluloid has largely moved to the Gitter:

https://gitter.im/celluloid/celluloid

**Comment by digitalextremist** [comment]
@dilumn?

**Comment by digitalextremist** [comment]
@tarcieri: @dilumn has expressed some interest ( and will likely come here and confirm that ) ... we've stayed in contact over the years since he came through `GSoC`. If a hit-list of items can be put together for him, I'm available to advise/mentor him as well; hopefully he will attract additional help around him.

**Comment by tarcieri** [comment]
@dilumn the main problems are there hasn't been a release in over two years (of 0.17 or 0.18), and there are a lot of open issues which have not been responded to.

**Comment by dilumn** [comment]
As the first thing, @tarcieri can you label the issues? So then we can have a look at them separately

**Comment by rmoriz** [comment]
Why did you delete https://github.com/celluloid/culture instead of just putting it in "read-only"/"archive" mode? :(

**Comment by tarcieri** [comment]
I merged its contents back into the respective repositories so it didn’t need to be a submodule anymore. Submodules are a pain in the ass to work with.

**Comment by valeronm** [comment]
@tarcieri deleting of https://github.com/celluloid/culture broken `bundle install` for all users who used unreleased version 0.17.4 from the "stable" branch `0-17-stable` because of annoying "Couldn't cleanly terminate all actors in 10 seconds!" message in 0.17.3

**Comment by tarcieri** [comment]
@valeronm that's unfortunate, and probably worth opening an separate issue about. If anyone still has a copy, I can put it back up.

**Comment by Esity** [comment]
@tarcieri  I am unsure of how much time I can spend on actual commits at this point but I do have bandwidth to help with maintaining repos, wikis, issues etc.  Let me know if you have any interest

**Comment by tarcieri** [comment]
@ngetahun @Esity if either of you would like to help, by all means go for it. I don't have a lot of time to advise / mentor right now, unfortunately (despite what I may have said earlier)

**Comment by Esity** [comment]
@ngetahun @digitalextremist @dilumn 
What do you guys think about getting a Slack channel running so we can start communicating about this stuff and get organized?

**Comment by tarcieri** [comment]
I can easily set up a Gitter, which I think is a little more easily discoverable as they're open to the public and support GitHub for federated identity

**Comment by tarcieri** [comment]
Oh hey, looks like we already have one https://gitter.im/celluloid

**Comment by dilumn** [comment]
Created one room https://gitter.im/celluloid/celluloid

**Comment by digitalextremist** [comment]
@tarcieri have two potential maintainers coming through and if not, will rearchive and re-open this.

**Comment by digitalextremist** [comment]
For posterity, details on the closing of this issue are:

@emesepadanyi took on the `Celluloid Revival` project, under my mentorship during `GSoC 2020`

Within that we have the support of @harsh183 and past `GSoC` alumni @dilumn, as well as several key participants from the past. We anticipate the refactoring process to be completed over the Summer ( in the Northern Hemisphere ) and then to be on track for `1.0` after that.

We are shooting for a "halfway" point of `0.5.0` after all the issues raised in #795, which is itself being updated now that the `Community Bonding` period is done, and `Coding Period 1` is well under way. For reference, check out the updates to `README.md` which include a diagram. The design being cleaned up, test suite being streamlined, and general housekeeping are going on now.

**Comment by kares** [comment]
Hey Donovam, #795 is really a great effort - looking forward for the (northern) summer!
One slight detail though, why 0.5.0 did you mean 0.50.0 (so that its > 0.17) before 1.0.0?

**Comment by harsh183** [comment]
That's correct. 0.50 is like a fixing and cleaning up the current rendition and idea of `celluloid`. The idea is that this just improves the experience of everyone using Celluloid at the moment. 

1.0 will take it to the next step and incorporate more interesting things.

**Comment by marek22k** [comment]
celluloid-io is an archive. Does the project still exist?

**Comment by digitalextremist** [comment]
@marek22k it is still here, just not actively maintained. Can I help you?

---

Update; saw your post:

> Hi there! I'm just looking for an alternative to EventMachine, since EM is no longer actively maintained and I came across celluloid-io. However, the repo is an archive. Is celluloid-io still being developed? If not, is there an alternative that is similar to EM or celluloid-io that you can recommend? (I don't like the async-io gem because of the complexity and lack of documentation).

Filling in the gaps between my last message and now: the `GSoC` project to revive `Celluloid` fell through under the circumstances at that time. A few people are still around the project, but it is not being actively developed. If you were interested in stepping in, plenty of people would know doubt pop up to advise and give history on objects and design decisions, etc. 

The language has evolved a lot since the last commits toward the core design being implemented rather than maintained or cleaned up. There is a lot to review before moving forward. That said `Celluloid` is still in wide use out there at various points in its version series. It is still a valid system to consider. Its concepts have still not been fully expressed, would be used widely if they were, and its simplicity and power is still unique.
